name: Anh Tu Phi
title: Tu's Engineering Blog
description: > 
  Tu's Engineering Blog solves technical issue.
avatar: https://avatars.githubusercontent.com/u/57997451?s=400&u=b2c45b9b533e13f8859507447c54bd892da2c554&v=4
url: https://anhtuphi.engineering.com

social_media:
  github: AnhTuPhi
  email: phianhtu2211@gmail.com
  viblo: https://viblo.asia/u/phianhtu2211
  substack: https://anhtuphi.substack.com/

disqus:
  shortname: AnhTuPhi

google_analytics:

post:
  date_format: '%-d %b %Y'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 8
paginate_path: "/blog/:num/"
encoding: UTF-8
gems: ['jekyll-paginate', 'jekyll-archives']

jekyll-archives:
  enabled: ['categories']
  layout: 'archive'
  permalinks:
    category: '/categories/:name/'

# Custom headers
webrick:
  headers:
    Content-Security-Policy: frame-ancestors 'none';
    X-Frame-Options: DENY
